DROP TABLE IF EXISTS METRICS_REPORT;

CREATE TABLE METRICS_REPORT
(
  REPORT_ID            	BIGINT        		NOT NULL,
  REPORT_NAME			VARCHAR(256)		NOT NULL,
  REPORT_TEMPLATE		VARCHAR(256)		NOT NULL,
  REPORT_OPTIONS		VARCHAR(4000)       ,
  REPORT_TYPE			VARCHAR(32)			NOT NULL,
  REPORT_CATEGORY		VARCHAR(32)			NOT NULL,
  SERIES_COLUMN			VARCHAR(1024)		,
  SERIES_VALUE			VARCHAR(1024)		NOT NULL,
  VALUE_COLUMNS			VARCHAR(256)		NOT NULL,
  EXECUTE_SQL			VARCHAR(1024) 		NOT NULL,
  PARAMETER_COLUMNS		VARCHAR(256) 		NOT NULL,
  ORDER_BY				VARCHAR(256),
  PRIMARY KEY (REPORT_ID)
);